import {
  Html5Icon,
  Css3Icon,
  JavaScriptIcon,
  VueDotjsIcon,
  LaravelIcon,
  PhpIcon,
  BootstrapIcon,
  TailwindCssIcon,
  JsonIcon,
  MySqlIcon,
  MongoDbIcon,
  TypeScriptIcon,
  GitIcon,
  JQueryIcon,
  ApolloGraphQlIcon,
  InstagramIcon,
  FacebookIcon,
  XIcon,
  LinkedInIcon,
  WhatsAppIcon,
} from 'vue3-simple-icons'

export default {
  Html5Icon,
  Css3Icon,
  JavaScriptIcon,
  VueDotjsIcon,
  LaravelIcon,
  PhpIcon,
  BootstrapIcon,
  TailwindCssIcon,
  JsonIcon,
  MySqlIcon,
  MongoDbIcon,
  TypeScriptIcon,
  GitIcon,
  JQueryIcon,
  ApolloGraphQlIcon,
  InstagramIcon,
  FacebookIcon,
  XIcon,
  LinkedInIcon,
  WhatsAppIcon,
}
